export enum FlutterEnum {
  DEAFULT = "Default (MVVM)",
  APIS = "Default, APIs",
  SB_APIS = "Default, Storybook, APIs",
  APIS_FIA = "Default, APIs, Feedback In App",
  APIS_UT = "Default, APIs, Unit Testing",
  SB_APIS_FIA = "Default, Storybook, APIs, Feedback In App",
  SB_APIS_UT = "Default, Storybook, APIs, Unit Testing",
  APIS_AY_CR = "Default, APIs, Analytics, Crash Report",
  APIS_FIA_UT = "Default, APIs, Feedback In App, Unit Testing",
  SB_APIS_AY_CR = "Default, Storybook, APIs, Analytics, Crash Report",
  SB_APIS_FIA_UT = "Default, Storybook, APIs, Feedback In App, Unit Testing",
  APIS_AY_CR_FIA = "Default, APIs, Analytics, Crash Report, Feedback In App",
  APIS_AY_CR_UT = "Default, APIs, Analytics, Crash Report, Unit Testing",
  SB_APIS_AY_CR_FIA = "Default, Storybook, APIs, Analytics, Crash Report, Feedback In App",
  SB_APIS_AY_CR_UT = "Default, Storybook, APIs, Analytics, Crash Report, Unit Testing",
  APIS_AY_CR_FIA_UT = "Default, APIs, Analytics, Crash Report, Feedback in App, Unit Testing",
  SB_APIS_AY_CR_FIA_UT = "Default, Storybook, APIs, Analytics, Crash Report, Feedback In App, Unit Testing",
}

export enum FlutterGHBranchesEnum {
  DEAFULT = "master",
  APIS = "apis",
  SB_APIS = "sb_apis",
  APIS_FIA = "apis_fia",
  APIS_UT = "apis_ut",
  SB_APIS_FIA = "sb_apis_fia",
  SB_APIS_UT = "sb_apis_ut",
  APIS_AY_CR = "apis_ay_cr",
  APIS_FIA_UT = "apis_fia_ut",
  SB_APIS_AY_CR = "sb_apis_ay_cr",
  SB_APIS_FIA_UT = "sb_apis_fia_ut",
  APIS_AY_CR_FIA = "apis_ay_cr_fia",
  APIS_AY_CR_UT = "apis_ay_cr_ut",
  SB_APIS_AY_CR_FIA = "sb_apis_ay_cr_fia",
  SB_APIS_AY_CR_UT = "sb_apis_ay_cr_ut",
  APIS_AY_CR_FIA_UT = "apis_ay_cr_fia_ut",
  SB_APIS_AY_CR_FIA_UT = "sb_apis_ay_cr_fia_ut",
}

export const flutterMethods = [
  FlutterEnum.DEAFULT,
  FlutterEnum.APIS,
  FlutterEnum.SB_APIS,
  FlutterEnum.APIS_FIA,
  FlutterEnum.APIS_UT,
  FlutterEnum.SB_APIS_FIA,
  FlutterEnum.SB_APIS_UT,
  FlutterEnum.APIS_AY_CR,
  FlutterEnum.APIS_FIA_UT,
  FlutterEnum.SB_APIS_AY_CR,
  FlutterEnum.SB_APIS_FIA_UT,
  FlutterEnum.APIS_AY_CR_FIA,
  FlutterEnum.APIS_AY_CR_UT,
  FlutterEnum.SB_APIS_AY_CR_FIA,
  FlutterEnum.SB_APIS_AY_CR_UT,
  FlutterEnum.APIS_AY_CR_FIA_UT,
  FlutterEnum.SB_APIS_AY_CR_FIA_UT,
]